# Generated by Django 5.1.1 on 2026-07-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmops', '0003_update_library_vietnamese'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculturalinput',
            name='active_ingredient_en',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='agriculturalinput',
            name='group_en',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='agriculturalinput',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='agriculturalinput',
            name='related_diseases_en',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agriculturalinput',
            name='safety_notes_en',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agriculturalinput',
            name='suitable_crops_en',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agriculturalinput',
            name='usage_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agriculturalinput',
            name='warning_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nutritionsymptom',
            name='affected_crops_en',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='nutritionsymptom',
            name='nutrient_en',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='nutritionsymptom',
            name='recommendation_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nutritionsymptom',
            name='safety_notes_en',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='nutritionsymptom',
            name='symptom_en',
            field=models.TextField(blank=True, default=''),
        ),
    ]
