"""Grow the agricultural input library from 3 demo rows to a usable catalogue.

Additive by construction: every row is inserted with ``get_or_create`` on its
natural key, so a database that already carries a row with the same name (or a
grower-specific edit of one) is left untouched. The reverse only removes the
names this migration introduces, which are disjoint from the 0002 seed.

The content is reference material for Vietnamese growers, matched to the crops
and diseases the diagnosis model recognises. It is deliberately generic about
dose and timing: the app never prescribes, it points at the label and the local
extension service.
"""

from django.db import migrations


INPUTS = [
    # --- Thuốc bảo vệ thực vật -------------------------------------------
    {
        "category": "pesticide",
        "name": "Thuốc trừ nấm gốc Mancozeb",
        "group": "Thuốc trừ nấm tiếp xúc",
        "active_ingredient": "Mancozeb",
        "usage": "Nhóm tiếp xúc phổ rộng, thường dùng phòng cháy lá sớm, cháy lá muộn và đốm lá trên cà chua, khoai tây, ngô.",
        "suitable_crops": ["cà chua", "khoai tây", "ngô", "bắp", "dưa chuột", "nho", "hành"],
        "related_diseases": ["cháy lá sớm", "cháy lá muộn", "đốm lá Septoria", "sương mai", "gỉ sắt"],
        "safety_notes": [
            "Phun phòng trước khi bệnh lan rộng, không phun khi trời sắp mưa.",
            "Mang khẩu trang, kính và găng tay khi pha thuốc.",
            "Luân phiên với hoạt chất khác nhóm để hạn chế kháng thuốc.",
        ],
        "withholding_period_days": 7,
        "warning": "Không tăng liều so với nhãn. Hỏi cán bộ bảo vệ thực vật trước khi dùng trên diện rộng.",
        "name_en": "Mancozeb fungicide",
        "group_en": "Contact fungicide",
        "active_ingredient_en": "Mancozeb",
        "usage_en": "A broad-spectrum contact group, commonly used to prevent early blight, late blight and leaf spot on tomato, potato and maize.",
        "suitable_crops_en": ["tomato", "potato", "maize", "cucumber", "grape", "onion"],
        "related_diseases_en": ["early blight", "late blight", "septoria leaf spot", "downy mildew", "rust"],
        "safety_notes_en": [
            "Spray preventively before the disease spreads; do not spray when rain is due.",
            "Wear a mask, goggles and gloves while mixing.",
            "Alternate with a different mode of action to slow resistance.",
        ],
        "warning_en": "Never exceed the label rate. Ask your local plant-protection officer before treating a large area.",
    },
    {
        "category": "pesticide",
        "name": "Thuốc trừ nấm gốc Chlorothalonil",
        "group": "Thuốc trừ nấm tiếp xúc",
        "active_ingredient": "Chlorothalonil",
        "usage": "Tham khảo cho đốm lá, mốc lá và cháy mép lá khi độ ẩm cao kéo dài.",
        "suitable_crops": ["cà chua", "dâu tây", "ớt chuông", "bí", "dưa chuột", "đậu tương"],
        "related_diseases": ["mốc lá", "đốm lá Septoria", "cháy mép lá", "đốm mục tiêu", "thán thư"],
        "safety_notes": [
            "Không phun vào lúc nắng gắt giữa trưa.",
            "Tránh xa ao cá và nguồn nước sinh hoạt.",
            "Không phun khi hoa đang nở rộ để bảo vệ ong.",
        ],
        "withholding_period_days": 7,
        "warning": "Chỉ dùng khi thật cần thiết và theo đúng nhãn. Ưu tiên biện pháp canh tác trước khi phun.",
        "name_en": "Chlorothalonil fungicide",
        "group_en": "Contact fungicide",
        "active_ingredient_en": "Chlorothalonil",
        "usage_en": "A reference option for leaf spot, leaf mould and leaf scorch during long humid spells.",
        "suitable_crops_en": ["tomato", "strawberry", "bell pepper", "squash", "cucumber", "soybean"],
        "related_diseases_en": ["leaf mold", "septoria leaf spot", "leaf scorch", "target spot", "anthracnose"],
        "safety_notes_en": [
            "Do not spray in the harsh midday sun.",
            "Keep well away from fish ponds and drinking-water sources.",
            "Do not spray during full bloom, to protect bees.",
        ],
        "warning_en": "Use only when genuinely needed and strictly per the label. Try cultural controls first.",
    },
    {
        "category": "pesticide",
        "name": "Thuốc trừ nấm gốc Azoxystrobin",
        "group": "Thuốc trừ nấm nội hấp",
        "active_ingredient": "Azoxystrobin",
        "usage": "Nhóm nội hấp, tham khảo cho gỉ sắt, phấn trắng và thán thư khi bệnh mới chớm.",
        "suitable_crops": ["cà phê", "nho", "xoài", "dâu tây", "ớt chuông", "bí", "chè"],
        "related_diseases": ["gỉ sắt", "bệnh phấn trắng", "thán thư", "đốm lá Cercospora"],
        "safety_notes": [
            "Không dùng liên tiếp quá 2 lần trong một vụ để tránh kháng thuốc.",
            "Pha đúng lượng nước để thuốc bám đều mặt dưới lá.",
        ],
        "withholding_period_days": 10,
        "warning": "Nhóm nội hấp dễ bị kháng nếu lạm dụng. Cần luân phiên hoạt chất theo khuyến cáo địa phương.",
        "name_en": "Azoxystrobin fungicide",
        "group_en": "Systemic fungicide",
        "active_ingredient_en": "Azoxystrobin",
        "usage_en": "A systemic group, referenced for rust, powdery mildew and anthracnose at the first signs of infection.",
        "suitable_crops_en": ["coffee", "grape", "mango", "strawberry", "bell pepper", "squash", "tea"],
        "related_diseases_en": ["rust", "powdery mildew", "anthracnose", "cercospora leaf spot"],
        "safety_notes_en": [
            "Do not apply more than twice in a row per season, to avoid resistance.",
            "Mix with enough water so the spray covers leaf undersides evenly.",
        ],
        "warning_en": "Systemic groups lose effect quickly when overused. Rotate active ingredients per local guidance.",
    },
    {
        "category": "pesticide",
        "name": "Thuốc trừ khuẩn gốc Streptomycin",
        "group": "Thuốc trừ vi khuẩn",
        "active_ingredient": "Streptomycin sulfate",
        "usage": "Tham khảo cho đốm vi khuẩn, bạc lá và loét vi khuẩn khi có xác nhận của cán bộ kỹ thuật.",
        "suitable_crops": ["cà chua", "ớt chuông", "đào", "cam", "lúa"],
        "related_diseases": ["đốm vi khuẩn", "bạc lá vi khuẩn", "loét vi khuẩn", "héo vi khuẩn"],
        "safety_notes": [
            "Chỉ phun khi đã xác định đúng là bệnh do vi khuẩn.",
            "Không phun ngay sau mưa vì thuốc dễ bị rửa trôi.",
            "Nhổ bỏ và tiêu hủy cây bệnh nặng thay vì phun thêm.",
        ],
        "withholding_period_days": 14,
        "warning": "Lạm dụng kháng sinh trên đồng ruộng gây kháng thuốc. Bắt buộc hỏi ý kiến cán bộ bảo vệ thực vật.",
        "name_en": "Streptomycin bactericide",
        "group_en": "Bactericide",
        "active_ingredient_en": "Streptomycin sulfate",
        "usage_en": "A reference option for bacterial spot, bacterial blight and canker once an expert has confirmed the cause.",
        "suitable_crops_en": ["tomato", "bell pepper", "peach", "orange", "rice"],
        "related_diseases_en": ["bacterial spot", "bacterial blight", "bacterial canker", "bacterial wilt"],
        "safety_notes_en": [
            "Spray only after confirming the problem really is bacterial.",
            "Do not spray right after rain; it washes off.",
            "Pull and destroy severely infected plants rather than spraying more.",
        ],
        "warning_en": "Overusing antibiotics in the field breeds resistance. Consult a plant-protection officer first.",
    },
    {
        "category": "pesticide",
        "name": "Dầu khoáng trừ nhện và rệp",
        "group": "Thuốc trừ sâu sinh học",
        "active_ingredient": "Dầu khoáng tinh chế (petroleum spray oil)",
        "usage": "Bao phủ và làm ngạt nhện đỏ, rệp sáp, bọ trĩ ở giai đoạn mật độ còn thấp.",
        "suitable_crops": ["cà chua", "cam", "chè", "cà phê", "hồ tiêu", "xoài", "dâu tây"],
        "related_diseases": ["nhện đỏ hai chấm", "nhện hại lá", "rệp sáp", "bọ trĩ", "nhện xanh"],
        "safety_notes": [
            "Không phun khi nhiệt độ trên 33 độ C vì dễ gây cháy lá.",
            "Không pha chung với thuốc gốc lưu huỳnh.",
            "Phun kỹ mặt dưới lá vì nhện thường trú ở đó.",
        ],
        "withholding_period_days": 3,
        "warning": "Thử trên vài cây trước khi phun cả vườn để kiểm tra cây có bị cháy lá không.",
        "name_en": "Horticultural mineral oil",
        "group_en": "Biological insecticide",
        "active_ingredient_en": "Refined petroleum spray oil",
        "usage_en": "Coats and suffocates spider mites, mealybugs and thrips while populations are still low.",
        "suitable_crops_en": ["tomato", "orange", "tea", "coffee", "black pepper", "mango", "strawberry"],
        "related_diseases_en": ["two-spotted spider mites", "mites", "mealybug", "thrips", "green mite"],
        "safety_notes_en": [
            "Do not spray above 33 degrees Celsius; it scorches leaves.",
            "Never tank-mix with sulphur products.",
            "Cover leaf undersides thoroughly, where mites live.",
        ],
        "warning_en": "Test on a few plants before treating the whole field, to check for leaf burn.",
    },
    {
        "category": "pesticide",
        "name": "Chế phẩm Bacillus thuringiensis (Bt)",
        "group": "Thuốc trừ sâu sinh học",
        "active_ingredient": "Bacillus thuringiensis",
        "usage": "Trừ sâu ăn lá tuổi nhỏ như sâu xanh, sâu khoang, sâu đục lá; an toàn hơn cho thiên địch.",
        "suitable_crops": ["cà chua", "ớt chuông", "bí", "ngô", "đậu tương", "chè", "dâu tây"],
        "related_diseases": ["sâu đục lá", "sâu ăn lá", "sâu xanh", "sâu khoang"],
        "safety_notes": [
            "Phun vào chiều mát vì ánh nắng làm giảm hiệu lực.",
            "Hiệu quả cao nhất khi sâu còn tuổi 1-2.",
            "Bảo quản nơi mát, không để nắng chiếu trực tiếp.",
        ],
        "withholding_period_days": 1,
        "warning": "Không diệt được sâu tuổi lớn. Cần kiểm tra vườn sớm để phun đúng thời điểm.",
        "name_en": "Bacillus thuringiensis (Bt) product",
        "group_en": "Biological insecticide",
        "active_ingredient_en": "Bacillus thuringiensis",
        "usage_en": "Controls young leaf-eating caterpillars such as armyworm and leaf miners, and is gentler on beneficial insects.",
        "suitable_crops_en": ["tomato", "bell pepper", "squash", "maize", "soybean", "tea", "strawberry"],
        "related_diseases_en": ["leaf miner", "leaf-eating caterpillar", "armyworm", "cutworm"],
        "safety_notes_en": [
            "Spray in the cool late afternoon; sunlight degrades it.",
            "Most effective on first and second instar larvae.",
            "Store somewhere cool and out of direct sunlight.",
        ],
        "warning_en": "It does not kill older larvae. Scout early so you can spray at the right moment.",
    },
    {
        "category": "pesticide",
        "name": "Chế phẩm nấm đối kháng Trichoderma",
        "group": "Chế phẩm sinh học đất",
        "active_ingredient": "Trichoderma spp.",
        "usage": "Ủ vào phân chuồng hoặc bón vào gốc để hạn chế nấm gây thối rễ, héo rũ và chết hom.",
        "suitable_crops": ["hồ tiêu", "cà phê", "sầu riêng", "cam", "cà chua", "dâu tây", "mía"],
        "related_diseases": ["thối rễ", "héo rũ", "thối hom", "chết nhanh chết chậm"],
        "safety_notes": [
            "Không trộn chung với thuốc trừ nấm hóa học.",
            "Giữ đất đủ ẩm sau khi bón để nấm phát triển.",
            "Dùng định kỳ đầu vụ, không đợi cây đã chết mới bón.",
        ],
        "withholding_period_days": None,
        "warning": "Là biện pháp phòng, không chữa được cây đã hỏng bộ rễ.",
        "name_en": "Trichoderma antagonistic fungus",
        "group_en": "Soil biological product",
        "active_ingredient_en": "Trichoderma spp.",
        "usage_en": "Composted into manure or applied at the root zone to suppress root rot, wilt and sett rot fungi.",
        "suitable_crops_en": ["black pepper", "coffee", "durian", "orange", "tomato", "strawberry", "sugarcane"],
        "related_diseases_en": ["root rot", "wilt", "sett rot", "quick and slow decline"],
        "safety_notes_en": [
            "Do not mix with chemical fungicides.",
            "Keep the soil moist afterwards so the fungus establishes.",
            "Apply routinely at the start of the season, not after the plant has collapsed.",
        ],
        "warning_en": "This is a preventive measure; it cannot restore a root system that has already failed.",
    },
    {
        "category": "pesticide",
        "name": "Vôi bột nông nghiệp",
        "group": "Xử lý đất",
        "active_ingredient": "CaO / CaCO3",
        "usage": "Rải xử lý đất đầu vụ để nâng pH, hạn chế nấm và tuyến trùng trong đất chua.",
        "suitable_crops": ["hồ tiêu", "cà phê", "cam", "lúa", "sắn", "mía", "chè"],
        "related_diseases": ["thối rễ", "héo vi khuẩn", "đất chua"],
        "safety_notes": [
            "Không bón vôi cùng lúc với phân đạm hoặc phân chuồng tươi.",
            "Chờ ít nhất 10-15 ngày sau khi bón vôi mới bón phân.",
            "Đeo khẩu trang và kính khi rải để tránh bụi vôi.",
        ],
        "withholding_period_days": None,
        "warning": "Bón quá nhiều vôi làm đất chai và khóa vi lượng. Nên đo pH đất trước khi bón.",
        "name_en": "Agricultural lime",
        "group_en": "Soil treatment",
        "active_ingredient_en": "CaO / CaCO3",
        "usage_en": "Spread at the start of the season to raise pH and suppress soil fungi and nematodes in acidic soils.",
        "suitable_crops_en": ["black pepper", "coffee", "orange", "rice", "cassava", "sugarcane", "tea"],
        "related_diseases_en": ["root rot", "bacterial wilt", "soil acidity"],
        "safety_notes_en": [
            "Do not apply lime together with nitrogen fertiliser or fresh manure.",
            "Wait 10-15 days after liming before fertilising.",
            "Wear a mask and goggles while spreading, to avoid lime dust.",
        ],
        "warning_en": "Over-liming compacts the soil and locks up micronutrients. Measure soil pH first.",
    },
    # --- Phân bón ----------------------------------------------------------
    {
        "category": "fertilizer",
        "name": "Phân urê (đạm)",
        "group": "Phân đơn đa lượng",
        "active_ingredient": "N 46%",
        "usage": "Bổ sung đạm giai đoạn phát triển thân lá, chia nhỏ nhiều lần thay vì bón dồn một lần.",
        "suitable_crops": ["lúa", "ngô", "cà chua", "chè", "mía", "sắn", "cà phê"],
        "related_diseases": ["thiếu đạm", "vàng lá", "cây còi cọc"],
        "safety_notes": [
            "Bón khi đất đủ ẩm, tránh bón lúc nắng gắt.",
            "Không bón sát gốc để tránh cháy rễ.",
            "Lấp đất hoặc tưới nhẹ sau khi bón để giảm bay hơi.",
        ],
        "withholding_period_days": None,
        "warning": "Bón thừa đạm làm cây rậm lá, mềm yếu và dễ nhiễm nấm bệnh hơn.",
        "name_en": "Urea (nitrogen)",
        "group_en": "Straight macronutrient fertilizer",
        "active_ingredient_en": "N 46%",
        "usage_en": "Supplies nitrogen during leaf and stem growth; split into several small doses rather than one heavy one.",
        "suitable_crops_en": ["rice", "maize", "tomato", "tea", "sugarcane", "cassava", "coffee"],
        "related_diseases_en": ["nitrogen deficiency", "leaf yellowing", "stunted growth"],
        "safety_notes_en": [
            "Apply when the soil is moist, never in harsh sun.",
            "Keep it away from the stem base to avoid root burn.",
            "Cover with soil or water lightly afterwards to limit volatilisation.",
        ],
        "warning_en": "Excess nitrogen makes growth soft and leafy, and far more prone to fungal disease.",
    },
    {
        "category": "fertilizer",
        "name": "Phân lân super",
        "group": "Phân đơn đa lượng",
        "active_ingredient": "P2O5 16%",
        "usage": "Bón lót đầu vụ để cây ra rễ khỏe, đặc biệt trên đất chua và đất mới khai hoang.",
        "suitable_crops": ["lúa", "ngô", "đậu tương", "khoai tây", "cà chua", "mía"],
        "related_diseases": ["thiếu lân", "rễ kém phát triển", "lá tím"],
        "safety_notes": [
            "Bón lót trước khi gieo trồng, trộn đều vào đất.",
            "Kết hợp với phân hữu cơ để tăng hiệu quả hấp thu.",
        ],
        "withholding_period_days": None,
        "warning": "Lân ít di chuyển trong đất nên bón muộn gần như không có tác dụng.",
        "name_en": "Single superphosphate",
        "group_en": "Straight macronutrient fertilizer",
        "active_ingredient_en": "P2O5 16%",
        "usage_en": "A basal dressing for strong root development, especially on acidic and newly cleared soils.",
        "suitable_crops_en": ["rice", "maize", "soybean", "potato", "tomato", "sugarcane"],
        "related_diseases_en": ["phosphorus deficiency", "poor root development", "purple leaves"],
        "safety_notes_en": [
            "Apply before planting and mix it evenly into the soil.",
            "Combine with organic matter to improve uptake.",
        ],
        "warning_en": "Phosphorus barely moves in soil, so a late application achieves almost nothing.",
    },
    {
        "category": "fertilizer",
        "name": "Phân kali clorua (KCl)",
        "group": "Phân đơn đa lượng",
        "active_ingredient": "K2O 60%",
        "usage": "Bổ sung kali giai đoạn nuôi trái, giúp trái chắc và cây chống chịu hạn tốt hơn.",
        "suitable_crops": ["cà chua", "khoai tây", "sầu riêng", "cam", "hồ tiêu", "mía", "cà phê"],
        "related_diseases": ["thiếu kali", "cháy rìa lá", "trái nhỏ"],
        "safety_notes": [
            "Hạn chế dùng KCl trên cây mẫn cảm với clo như chè và thuốc lá.",
            "Chia làm nhiều lần bón trong giai đoạn nuôi trái.",
        ],
        "withholding_period_days": None,
        "warning": "Bón kali quá tay gây mất cân đối với canxi và magie, dẫn tới thối đít trái.",
        "name_en": "Muriate of potash (KCl)",
        "group_en": "Straight macronutrient fertilizer",
        "active_ingredient_en": "K2O 60%",
        "usage_en": "Supplies potassium during fruit filling, for firmer fruit and better drought tolerance.",
        "suitable_crops_en": ["tomato", "potato", "durian", "orange", "black pepper", "sugarcane", "coffee"],
        "related_diseases_en": ["potassium deficiency", "leaf margin scorch", "small fruit"],
        "safety_notes_en": [
            "Limit KCl on chloride-sensitive crops such as tea and tobacco.",
            "Split it across several applications during fruit filling.",
        ],
        "warning_en": "Too much potassium unbalances calcium and magnesium and can trigger blossom-end rot.",
    },
    {
        "category": "fertilizer",
        "name": "Phân hữu cơ hoai mục",
        "group": "Phân hữu cơ",
        "active_ingredient": "Chất hữu cơ, mùn",
        "usage": "Bón lót cải tạo đất, giữ ẩm và nuôi hệ vi sinh vật có lợi trong đất.",
        "suitable_crops": ["cà chua", "dâu tây", "ớt chuông", "cà phê", "hồ tiêu", "cam", "sầu riêng", "chè"],
        "related_diseases": ["đất bạc màu", "thiếu dinh dưỡng", "rễ kém phát triển"],
        "safety_notes": [
            "Chỉ dùng phân đã hoai mục hoàn toàn, phân tươi mang mầm bệnh và gây cháy rễ.",
            "Ủ cùng Trichoderma để tăng khả năng đối kháng nấm đất.",
        ],
        "withholding_period_days": None,
        "warning": "Phân chuồng tươi là nguồn lây vi khuẩn cho rau ăn lá. Bắt buộc ủ đúng cách.",
        "name_en": "Well-rotted organic manure",
        "group_en": "Organic fertilizer",
        "active_ingredient_en": "Organic matter, humus",
        "usage_en": "A basal dressing that rebuilds soil structure, holds moisture and feeds beneficial soil life.",
        "suitable_crops_en": ["tomato", "strawberry", "bell pepper", "coffee", "black pepper", "orange", "durian", "tea"],
        "related_diseases_en": ["depleted soil", "nutrient deficiency", "poor root development"],
        "safety_notes_en": [
            "Use only fully composted manure; fresh manure carries pathogens and burns roots.",
            "Compost it with Trichoderma to add protection against soil fungi.",
        ],
        "warning_en": "Fresh manure is a bacterial risk on leafy vegetables. It must be properly composted.",
    },
    {
        "category": "fertilizer",
        "name": "Phân NPK 16-16-8 chuyên rau màu",
        "group": "Phân hỗn hợp",
        "active_ingredient": "N-P-K 16-16-8",
        "usage": "Bón thúc cho rau màu và cây ngắn ngày trong giai đoạn sinh trưởng mạnh.",
        "suitable_crops": ["cà chua", "ớt chuông", "dưa chuột", "bí", "khoai tây", "đậu tương", "ngô"],
        "related_diseases": ["thiếu dinh dưỡng", "cây còi cọc"],
        "safety_notes": [
            "Bón cách gốc 10-15 cm rồi lấp đất và tưới nhẹ.",
            "Không bón khi đất đang khô hạn nặng.",
        ],
        "withholding_period_days": None,
        "warning": "Công thức chung không thay thế được kết quả phân tích đất của từng vườn.",
        "name_en": "NPK 16-16-8 for vegetables",
        "group_en": "Compound fertilizer",
        "active_ingredient_en": "N-P-K 16-16-8",
        "usage_en": "A top dressing for vegetables and short-cycle crops during rapid growth.",
        "suitable_crops_en": ["tomato", "bell pepper", "cucumber", "squash", "potato", "soybean", "maize"],
        "related_diseases_en": ["nutrient deficiency", "stunted growth"],
        "safety_notes_en": [
            "Place it 10-15 cm from the stem, cover with soil and water lightly.",
            "Do not apply while the soil is severely dry.",
        ],
        "warning_en": "A generic ratio is no substitute for a soil test on your own field.",
    },
    {
        "category": "fertilizer",
        "name": "Phân NPK 15-5-20 chuyên nuôi trái",
        "group": "Phân hỗn hợp",
        "active_ingredient": "N-P-K 15-5-20",
        "usage": "Bón giai đoạn nuôi trái cho cây ăn quả và cây công nghiệp, ưu tiên kali.",
        "suitable_crops": ["sầu riêng", "cam", "xoài", "nho", "cà phê", "hồ tiêu", "cà chua"],
        "related_diseases": ["thiếu kali", "trái nhỏ", "rụng trái non"],
        "safety_notes": [
            "Bón theo tán cây, không bón dồn vào một điểm.",
            "Kết hợp tưới đủ ẩm để cây hấp thu được.",
        ],
        "withholding_period_days": None,
        "warning": "Cần cân đối thêm canxi và magie, nếu không trái dễ nứt và thối đít.",
        "name_en": "NPK 15-5-20 for fruiting",
        "group_en": "Compound fertilizer",
        "active_ingredient_en": "N-P-K 15-5-20",
        "usage_en": "A potassium-led blend for the fruiting stage of orchard and industrial crops.",
        "suitable_crops_en": ["durian", "orange", "mango", "grape", "coffee", "black pepper", "tomato"],
        "related_diseases_en": ["potassium deficiency", "small fruit", "fruit drop"],
        "safety_notes_en": [
            "Spread it under the canopy rather than in one spot.",
            "Water afterwards so the crop can actually take it up.",
        ],
        "warning_en": "Balance it with calcium and magnesium, or fruit will crack and develop blossom-end rot.",
    },
    {
        "category": "fertilizer",
        "name": "Phân bón lá vi lượng tổng hợp",
        "group": "Phân bón lá",
        "active_ingredient": "Zn, B, Mn, Fe, Cu, Mo",
        "usage": "Phun bổ sung vi lượng khi lá non biến dạng, xoăn hoặc bạc màu giữa các gân.",
        "suitable_crops": ["cam", "cà phê", "sầu riêng", "cà chua", "nho", "xoài", "dâu tây"],
        "related_diseases": ["thiếu vi lượng", "xoăn lá", "vàng lá gân xanh", "rụng hoa"],
        "safety_notes": [
            "Phun vào sáng sớm hoặc chiều mát để lá hấp thu tốt.",
            "Không phun chồng nhiều loại phân bón lá cùng lúc.",
        ],
        "withholding_period_days": None,
        "warning": "Phân bón lá chỉ hỗ trợ, không thay thế việc xử lý pH đất và bón gốc.",
        "name_en": "Foliar micronutrient blend",
        "group_en": "Foliar fertilizer",
        "active_ingredient_en": "Zn, B, Mn, Fe, Cu, Mo",
        "usage_en": "A foliar top-up when young leaves are distorted, curled or pale between the veins.",
        "suitable_crops_en": ["orange", "coffee", "durian", "tomato", "grape", "mango", "strawberry"],
        "related_diseases_en": ["micronutrient deficiency", "leaf curl", "citrus greening symptoms", "flower drop"],
        "safety_notes_en": [
            "Spray in the early morning or cool late afternoon for better uptake.",
            "Do not stack several foliar products in one spray.",
        ],
        "warning_en": "Foliar feeding only supports the crop; it does not replace fixing soil pH and root feeding.",
    },
    # --- Dinh dưỡng --------------------------------------------------------
    {
        "category": "nutrition",
        "name": "Canxi nitrat chống thối đít trái",
        "group": "Dinh dưỡng trung lượng",
        "active_ingredient": "Ca(NO3)2",
        "usage": "Bổ sung canxi giai đoạn đậu trái để hạn chế thối đít trái trên cà chua và ớt.",
        "suitable_crops": ["cà chua", "ớt chuông", "dưa chuột", "bí", "dâu tây"],
        "related_diseases": ["thối đít trái", "thiếu canxi", "nứt trái"],
        "safety_notes": [
            "Không pha chung với phân lân hoặc sunfat vì sẽ kết tủa.",
            "Giữ ẩm đất đều, vì thiếu nước làm cây không hút được canxi dù đất đủ.",
        ],
        "withholding_period_days": None,
        "warning": "Thối đít trái thường do tưới không đều hơn là do đất thiếu canxi. Kiểm tra chế độ tưới trước.",
        "name_en": "Calcium nitrate for blossom-end rot",
        "group_en": "Secondary nutrient",
        "active_ingredient_en": "Ca(NO3)2",
        "usage_en": "Supplies calcium at fruit set to limit blossom-end rot on tomato and pepper.",
        "suitable_crops_en": ["tomato", "bell pepper", "cucumber", "squash", "strawberry"],
        "related_diseases_en": ["blossom-end rot", "calcium deficiency", "fruit cracking"],
        "safety_notes_en": [
            "Never tank-mix with phosphate or sulphate products; they precipitate.",
            "Keep soil moisture even: erratic watering blocks calcium uptake even in calcium-rich soil.",
        ],
        "warning_en": "Blossom-end rot is more often an irrigation problem than a soil-calcium one. Check watering first.",
    },
    {
        "category": "nutrition",
        "name": "Magie sunfat (MgSO4)",
        "group": "Dinh dưỡng trung lượng",
        "active_ingredient": "MgO, S",
        "usage": "Bổ sung magie và lưu huỳnh khi lá già vàng giữa gân mà gân vẫn xanh.",
        "suitable_crops": ["cà phê", "cam", "hồ tiêu", "sầu riêng", "nho", "cà chua", "chè"],
        "related_diseases": ["thiếu magie", "vàng lá giữa gân", "thiếu lưu huỳnh"],
        "safety_notes": [
            "Có thể phun qua lá với nồng độ loãng khi cần khắc phục nhanh.",
            "Kiểm tra pH đất, vì đất quá chua làm cây khó hút magie.",
        ],
        "withholding_period_days": None,
        "warning": "Bón kali quá nhiều sẽ cản trở cây hút magie. Cần xem lại toàn bộ công thức phân.",
        "name_en": "Magnesium sulphate (MgSO4)",
        "group_en": "Secondary nutrient",
        "active_ingredient_en": "MgO, S",
        "usage_en": "Supplies magnesium and sulphur when older leaves yellow between the veins while the veins stay green.",
        "suitable_crops_en": ["coffee", "orange", "black pepper", "durian", "grape", "tomato", "tea"],
        "related_diseases_en": ["magnesium deficiency", "interveinal chlorosis", "sulphur deficiency"],
        "safety_notes_en": [
            "It can be sprayed as a dilute foliar feed for a quick correction.",
            "Check soil pH: very acidic soil blocks magnesium uptake.",
        ],
        "warning_en": "Heavy potassium feeding blocks magnesium uptake. Review the whole fertiliser programme.",
    },
    {
        "category": "nutrition",
        "name": "Kẽm chelate (Zn-EDTA)",
        "group": "Vi lượng",
        "active_ingredient": "Zn chelate",
        "usage": "Khắc phục lá non nhỏ, mọc chụm và bạc màu giữa gân trên cây có múi và cà phê.",
        "suitable_crops": ["cam", "cà phê", "xoài", "ngô", "lúa", "sầu riêng"],
        "related_diseases": ["thiếu kẽm", "lá nhỏ mọc chụm", "vàng lá gân xanh"],
        "safety_notes": [
            "Phun đúng nồng độ, quá liều gây cháy lá non.",
            "Triệu chứng thiếu kẽm rất giống bệnh vàng lá gân xanh, cần phân biệt kỹ.",
        ],
        "withholding_period_days": None,
        "warning": "Nếu cây có múi vàng lá gân xanh kèm trái méo, hãy nghi ngờ bệnh Greening và báo cán bộ kỹ thuật.",
        "name_en": "Chelated zinc (Zn-EDTA)",
        "group_en": "Micronutrient",
        "active_ingredient_en": "Zn chelate",
        "usage_en": "Corrects small, rosetted and interveinal-pale young leaves on citrus and coffee.",
        "suitable_crops_en": ["orange", "coffee", "mango", "maize", "rice", "durian"],
        "related_diseases_en": ["zinc deficiency", "little leaf rosette", "citrus greening symptoms"],
        "safety_notes_en": [
            "Respect the rate; an overdose scorches young leaves.",
            "Zinc deficiency looks very similar to citrus greening, so distinguish carefully.",
        ],
        "warning_en": "Citrus with interveinal yellowing plus lopsided fruit may have Greening. Report it to an extension officer.",
    },
    {
        "category": "nutrition",
        "name": "Bo (Boron) dạng borax nông nghiệp",
        "group": "Vi lượng",
        "active_ingredient": "B",
        "usage": "Hỗ trợ đậu trái, giảm rụng hoa và nứt trái trên cây ăn quả và rau ăn quả.",
        "suitable_crops": ["sầu riêng", "cam", "xoài", "cà chua", "ớt chuông", "dâu tây"],
        "related_diseases": ["thiếu bo", "rụng hoa", "nứt trái", "chết đỉnh sinh trưởng"],
        "safety_notes": [
            "Khoảng an toàn của bo rất hẹp, thừa bo gây ngộ độc và cháy mép lá.",
            "Chỉ bổ sung khi có dấu hiệu rõ hoặc có kết quả phân tích lá.",
        ],
        "withholding_period_days": None,
        "warning": "Không tự tăng liều bo. Thừa bo gây hại nhanh và khó khắc phục hơn thiếu bo.",
        "name_en": "Boron (agricultural borax)",
        "group_en": "Micronutrient",
        "active_ingredient_en": "B",
        "usage_en": "Supports fruit set and reduces flower drop and fruit cracking on orchard and fruiting vegetables.",
        "suitable_crops_en": ["durian", "orange", "mango", "tomato", "bell pepper", "strawberry"],
        "related_diseases_en": ["boron deficiency", "flower drop", "fruit cracking", "growing-point dieback"],
        "safety_notes_en": [
            "Boron has a very narrow safe range; an excess is toxic and scorches leaf margins.",
            "Apply only on clear symptoms or a leaf-analysis result.",
        ],
        "warning_en": "Never raise the boron rate on your own. Excess boron does more damage, faster, than a deficiency.",
    },
    {
        "category": "nutrition",
        "name": "Axit humic - fulvic cải tạo đất",
        "group": "Cải tạo đất",
        "active_ingredient": "Humic acid, fulvic acid",
        "usage": "Tưới gốc để tăng khả năng giữ dinh dưỡng của đất và kích thích bộ rễ phục hồi.",
        "suitable_crops": ["cà phê", "hồ tiêu", "sầu riêng", "cam", "cà chua", "dâu tây", "chè", "mía"],
        "related_diseases": ["đất bạc màu", "rễ kém phát triển", "cây phục hồi chậm sau bệnh"],
        "safety_notes": [
            "Tưới khi đất đủ ẩm, không tưới lên cây đang héo do thiếu nước.",
            "Không thay thế phân bón, chỉ giúp cây hấp thu tốt hơn.",
        ],
        "withholding_period_days": None,
        "warning": "Không có tác dụng chữa bệnh. Cây bệnh nặng vẫn cần xử lý nguyên nhân gốc.",
        "name_en": "Humic - fulvic soil conditioner",
        "group_en": "Soil conditioner",
        "active_ingredient_en": "Humic acid, fulvic acid",
        "usage_en": "Applied at the root zone to improve nutrient retention and help the root system recover.",
        "suitable_crops_en": ["coffee", "black pepper", "durian", "orange", "tomato", "strawberry", "tea", "sugarcane"],
        "related_diseases_en": ["depleted soil", "poor root development", "slow recovery after disease"],
        "safety_notes_en": [
            "Apply to moist soil; never onto a crop already wilting from drought.",
            "It does not replace fertiliser, it only improves uptake.",
        ],
        "warning_en": "It is not a treatment. A badly diseased plant still needs the underlying cause addressed.",
    },
    {
        "category": "nutrition",
        "name": "Silic dạng silicat cho lúa và mía",
        "group": "Dinh dưỡng bổ sung",
        "active_ingredient": "SiO2",
        "usage": "Giúp thân lá cứng cáp hơn, hạn chế đổ ngã và giảm áp lực sâu bệnh trên lúa, mía, ngô.",
        "suitable_crops": ["lúa", "mía", "ngô", "chè"],
        "related_diseases": ["đổ ngã", "đạo ôn", "đốm nâu", "bạc lá vi khuẩn"],
        "safety_notes": [
            "Bón lót hoặc bón thúc sớm, hiệu quả thấp nếu bón muộn.",
            "Không thay thế thuốc bảo vệ thực vật khi bệnh đã bùng phát.",
        ],
        "withholding_period_days": None,
        "warning": "Là biện pháp hỗ trợ phòng ngừa, cần kết hợp với giống kháng và mật độ gieo hợp lý.",
        "name_en": "Silicate silicon for rice and sugarcane",
        "group_en": "Supplementary nutrition",
        "active_ingredient_en": "SiO2",
        "usage_en": "Strengthens stems and leaves, limiting lodging and easing pest pressure on rice, sugarcane and maize.",
        "suitable_crops_en": ["rice", "sugarcane", "maize", "tea"],
        "related_diseases_en": ["lodging", "rice blast", "brown spot", "bacterial blight"],
        "safety_notes_en": [
            "Apply as a basal or early top dressing; a late application achieves little.",
            "It does not replace crop protection once an outbreak is under way.",
        ],
        "warning_en": "This is preventive support only; pair it with resistant varieties and sensible planting density.",
    },
]

SYMPTOMS = [
    {
        "nutrient": "Thiếu lân",
        "symptom": "Lá già chuyển xanh sẫm rồi ánh tím ở mặt dưới, rễ ít, cây chậm lớn và ra hoa muộn.",
        "affected_crops": ["ngô", "lúa", "cà chua", "khoai tây", "đậu tương"],
        "recommendation": "Kiểm tra pH đất, bón lót lân sớm và kết hợp phân hữu cơ hoai mục để cây ra rễ.",
        "safety_notes": ["Bón lân muộn gần như không có tác dụng vì lân ít di chuyển trong đất."],
        "nutrient_en": "Phosphorus deficiency",
        "symptom_en": "Older leaves turn dark green then purplish underneath, roots are sparse, growth and flowering are late.",
        "affected_crops_en": ["maize", "rice", "tomato", "potato", "soybean"],
        "recommendation_en": "Check soil pH, apply phosphorus early as a basal dressing and combine it with composted manure.",
        "safety_notes_en": ["A late phosphorus application achieves almost nothing, because it barely moves in soil."],
    },
    {
        "nutrient": "Thiếu canxi",
        "symptom": "Đỉnh sinh trưởng và lá non biến dạng, trái cà chua và ớt bị thối đen ở đáy trái.",
        "affected_crops": ["cà chua", "ớt chuông", "dưa chuột", "bí", "dâu tây"],
        "recommendation": "Giữ ẩm đất đều đặn và bổ sung canxi giai đoạn đậu trái theo khuyến cáo địa phương.",
        "safety_notes": ["Tưới thất thường là nguyên nhân phổ biến hơn cả đất nghèo canxi."],
        "nutrient_en": "Calcium deficiency",
        "symptom_en": "Growing points and young leaves distort, and tomato or pepper fruit rots black at the blossom end.",
        "affected_crops_en": ["tomato", "bell pepper", "cucumber", "squash", "strawberry"],
        "recommendation_en": "Keep soil moisture even and add calcium at fruit set, following local recommendations.",
        "safety_notes_en": ["Erratic watering causes this far more often than genuinely calcium-poor soil."],
    },
    {
        "nutrient": "Thiếu kẽm",
        "symptom": "Lá non nhỏ, mọc chụm thành cụm ở đầu cành, bạc màu giữa các gân lá.",
        "affected_crops": ["cam", "cà phê", "ngô", "lúa", "xoài"],
        "recommendation": "Đối chiếu với triệu chứng vàng lá gân xanh trước khi kết luận, sau đó cân nhắc bổ sung kẽm chelate.",
        "safety_notes": [
            "Trên cây có múi, nếu kèm trái méo và hạt lép thì phải nghi ngờ bệnh Greening và báo cán bộ kỹ thuật."
        ],
        "nutrient_en": "Zinc deficiency",
        "symptom_en": "Young leaves stay small and rosette at the shoot tips, with pale tissue between the veins.",
        "affected_crops_en": ["orange", "coffee", "maize", "rice", "mango"],
        "recommendation_en": "Rule out citrus greening first, then consider a chelated zinc application.",
        "safety_notes_en": [
            "On citrus, lopsided fruit and aborted seeds alongside this pattern point to Greening; report it to an extension officer."
        ],
    },
    {
        "nutrient": "Thiếu sắt",
        "symptom": "Lá non vàng nhạt gần như trắng, gân lá vẫn xanh rõ, thường thấy trên đất kiềm hoặc đất úng.",
        "affected_crops": ["cam", "sầu riêng", "nho", "dâu tây", "cà chua"],
        "recommendation": "Kiểm tra thoát nước và pH đất trước, vì thừa vôi và đất úng làm rễ không hút được sắt.",
        "safety_notes": ["Bón thêm sắt mà không xử lý pH và thoát nước thường không cải thiện được gì."],
        "nutrient_en": "Iron deficiency",
        "symptom_en": "Young leaves go pale yellow to almost white while the veins stay clearly green, typically on alkaline or waterlogged soil.",
        "affected_crops_en": ["orange", "durian", "grape", "strawberry", "tomato"],
        "recommendation_en": "Check drainage and soil pH first: excess lime and waterlogging stop roots taking up iron.",
        "safety_notes_en": ["Adding iron without fixing pH and drainage usually changes nothing."],
    },
    {
        "nutrient": "Thiếu bo",
        "symptom": "Đỉnh sinh trưởng chết, hoa rụng nhiều, trái nứt hoặc méo và ruột trái bị rỗng.",
        "affected_crops": ["sầu riêng", "cam", "cà chua", "xoài", "ớt chuông"],
        "recommendation": "Bổ sung bo rất thận trọng theo đúng liều khuyến cáo, tốt nhất là sau khi phân tích lá.",
        "safety_notes": ["Khoảng an toàn của bo rất hẹp: thừa bo gây cháy mép lá và hại nhanh hơn thiếu bo."],
        "nutrient_en": "Boron deficiency",
        "symptom_en": "Growing points die back, flowers drop heavily, and fruit cracks or deforms with hollow flesh.",
        "affected_crops_en": ["durian", "orange", "tomato", "mango", "bell pepper"],
        "recommendation_en": "Add boron very cautiously at the recommended rate, ideally after a leaf analysis.",
        "safety_notes_en": ["Boron has a very narrow safe range: an excess scorches leaf margins and harms faster than a shortage."],
    },
    {
        "nutrient": "Thiếu lưu huỳnh",
        "symptom": "Lá non vàng đều cả phiến lá, khác với thiếu đạm là vàng từ lá già trước.",
        "affected_crops": ["cà phê", "chè", "đậu tương", "lúa", "ngô"],
        "recommendation": "Cân nhắc nguồn phân có chứa lưu huỳnh như magie sunfat hoặc phân đơn chứa S.",
        "safety_notes": ["Dễ nhầm với thiếu đạm, nên xem kỹ vàng ở lá non hay lá già trước khi bón."],
        "nutrient_en": "Sulphur deficiency",
        "symptom_en": "Young leaves yellow uniformly across the whole blade, unlike nitrogen deficiency which starts on older leaves.",
        "affected_crops_en": ["coffee", "tea", "soybean", "rice", "maize"],
        "recommendation_en": "Consider a sulphur-bearing source such as magnesium sulphate or a straight S fertiliser.",
        "safety_notes_en": ["Easily confused with nitrogen deficiency; check whether the young or the old leaves yellow first."],
    },
    {
        "nutrient": "Thiếu mangan",
        "symptom": "Vàng giữa gân trên lá non kèm những đốm hoại tử nhỏ, gân chính vẫn xanh.",
        "affected_crops": ["đậu tương", "lúa", "cam", "nho", "chè"],
        "recommendation": "Kiểm tra pH đất, vì đất kiềm và đất bón vôi quá tay thường khóa mangan.",
        "safety_notes": ["Triệu chứng gần giống thiếu sắt, cần đối chiếu thực địa trước khi bổ sung."],
        "nutrient_en": "Manganese deficiency",
        "symptom_en": "Interveinal yellowing on young leaves with small necrotic flecks, while the main veins stay green.",
        "affected_crops_en": ["soybean", "rice", "orange", "grape", "tea"],
        "recommendation_en": "Check soil pH: alkaline and over-limed soils commonly lock up manganese.",
        "safety_notes_en": ["It closely resembles iron deficiency; confirm in the field before treating."],
    },
    {
        "nutrient": "Thừa đạm",
        "symptom": "Cây rậm lá xanh đậm, thân mềm, ra hoa đậu trái kém và rất dễ nhiễm nấm bệnh.",
        "affected_crops": ["cà chua", "lúa", "chè", "cà phê", "dâu tây"],
        "recommendation": "Giảm và chia nhỏ lượng đạm, tăng kali và thông thoáng tán để giảm áp lực bệnh.",
        "safety_notes": ["Vườn thừa đạm cần theo dõi sâu bệnh dày hơn, đặc biệt là bệnh nấm trên lá."],
        "nutrient_en": "Nitrogen excess",
        "symptom_en": "Dense dark-green foliage, soft stems, poor flowering and fruit set, and a high susceptibility to fungal disease.",
        "affected_crops_en": ["tomato", "rice", "tea", "coffee", "strawberry"],
        "recommendation_en": "Cut and split the nitrogen, raise potassium and open up the canopy to reduce disease pressure.",
        "safety_notes_en": ["An over-fed field needs closer pest scouting, especially for foliar fungal disease."],
    },
]


def seed(apps, schema_editor):
    AgriculturalInput = apps.get_model("farmops", "AgriculturalInput")
    NutritionSymptom = apps.get_model("farmops", "NutritionSymptom")

    for item in INPUTS:
        # get_or_create, not update_or_create: a row that already carries this
        # name may have been edited on purpose and must not be overwritten.
        AgriculturalInput.objects.get_or_create(name=item["name"], defaults=item)
    for item in SYMPTOMS:
        NutritionSymptom.objects.get_or_create(nutrient=item["nutrient"], defaults=item)


def unseed(apps, schema_editor):
    AgriculturalInput = apps.get_model("farmops", "AgriculturalInput")
    NutritionSymptom = apps.get_model("farmops", "NutritionSymptom")

    AgriculturalInput.objects.filter(name__in=[item["name"] for item in INPUTS]).delete()
    NutritionSymptom.objects.filter(nutrient__in=[item["nutrient"] for item in SYMPTOMS]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("farmops", "0005_seed_library_english"),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
