# Generated by Django 5.1.1 on 2026-07-22 06:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0004_sync_billing_plans'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='transfer_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='old_plan',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan_requested',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Cho xu ly'), ('success', 'Thanh cong'), ('underpaid', 'Thieu tien'), ('overpaid', 'Thua tien'), ('unmatched', 'Khong khop don'), ('late', 'Thanh toan sau khi het han'), ('failed', 'That bai'), ('ignored', 'Bo qua')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('amount_expected', models.PositiveBigIntegerField()),
                ('amount_received', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(default='VND', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Cho thanh toan'), ('underpaid', 'Thieu tien'), ('paid', 'Da thanh toan'), ('overpaid', 'Thua tien - can doi soat'), ('expired', 'Het han'), ('cancelled', 'Da huy'), ('review', 'Can doi soat')], default='pending', max_length=20)),
                ('provider', models.CharField(default='sepay', max_length=30)),
                ('expires_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='engagement.serviceplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.paymentorder'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['user', 'status', '-created_at'], name='pay_order_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['status', 'expires_at'], name='pay_order_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentorder',
            constraint=models.CheckConstraint(condition=models.Q(('amount_expected__gt', 0)), name='payment_order_expected_positive'),
        ),
    ]
