# Generated by Django 5.1.1 on 2026-08-01 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_account_number_payment_processed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_token', models.CharField(db_index=True, max_length=512, unique=True)),
                ('product_id', models.CharField(max_length=120)),
                ('package_name', models.CharField(blank=True, default='', max_length=180)),
                ('plan', models.CharField(blank=True, default='', max_length=30)),
                ('state', models.CharField(choices=[('pending', 'Cho Google xac nhan'), ('granted', 'Da cap quyen'), ('cancelled', 'Da huy'), ('expired', 'Het han'), ('refunded', 'Da hoan tien')], default='pending', max_length=20)),
                ('acknowledged', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('client_request_id', models.CharField(blank=True, default='', max_length=64)),
                ('raw_state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='play_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
