# Generated by Django 5.1.1 on 2026-07-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_plans', '0003_update_seeded_crops_vietnamese'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropplan',
            name='ai_reasoning_summary_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cropplan',
            name='summary_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cropplan',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='cropplanstep',
            name='completion_condition_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cropplanstep',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cropplanstep',
            name='fertilizer_amount_unit_en',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='cropplanstep',
            name='prerequisites_en',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cropplanstep',
            name='risk_notes_en',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cropplanstep',
            name='short_label_en',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='cropplanstep',
            name='sunlight_requirement_text_en',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='cropplanstep',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='cropplanstep',
            name='tools_needed_en',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cropplanstep',
            name='water_amount_unit_en',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='cropplanstep',
            name='why_this_step_matters_en',
            field=models.TextField(blank=True, default=''),
        ),
    ]
