# Generated by Django 5.1.1 on 2026-07-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_plans', '0004_cropplan_ai_reasoning_summary_en_cropplan_summary_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='crop',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
