# Generated by Django 5.1.1 on 2026-07-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_plans', '0006_seed_crop_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='body_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reminder',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
    ]
