# Generated by Django 5.1.1 on 2026-07-25 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_plans', '0007_reminder_body_en_reminder_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='completionlog',
            name='step_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completionlog',
            name='step_title',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='completionlog',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_logs', to='crop_plans.cropplanstep'),
        ),
        migrations.AlterField(
            model_name='cropplan',
            name='suitability_score',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
