// Nội dung pháp lý song ngữ cho Agromind AI.
// Lưu ý: đây là bản soạn sẵn chi tiết, nên được luật sư rà soát trước khi
// dùng chính thức. Cập nhật CONTACT_EMAIL bằng email liên hệ thật của bạn.

export const CONTACT_EMAIL = "phamduccmanhh@gmail.com";
export const LEGAL_UPDATED = { vi: "Cập nhật lần cuối: 25/07/2026", en: "Last updated: July 25, 2026" };

type Bi = { vi: string; en: string };
type BiList = { vi: string[]; en: string[] };

export interface LegalSection {
  heading: Bi;
  body?: Bi;
  list?: BiList;
}

export interface LegalDoc {
  title: Bi;
  intro: Bi;
  sections: LegalSection[];
}

export const termsDoc: LegalDoc = {
  title: { vi: "Điều khoản sử dụng", en: "Terms of Service" },
  intro: {
    vi: "Chào mừng bạn đến với Agromind AI. Các Điều khoản sử dụng này (“Điều khoản”) điều chỉnh việc bạn truy cập và sử dụng website, ứng dụng và các dịch vụ của Agromind AI (“Dịch vụ”). Bằng việc tạo tài khoản hoặc sử dụng Dịch vụ, bạn xác nhận đã đọc, hiểu và đồng ý bị ràng buộc bởi các Điều khoản này cùng Chính sách quyền riêng tư. Nếu bạn không đồng ý, vui lòng không sử dụng Dịch vụ.",
    en: "Welcome to Agromind AI. These Terms of Service (“Terms”) govern your access to and use of the Agromind AI website, application and services (the “Service”). By creating an account or using the Service, you confirm that you have read, understood and agree to be bound by these Terms and the Privacy Policy. If you do not agree, please do not use the Service.",
  },
  sections: [
    {
      heading: { vi: "1. Chấp nhận điều khoản", en: "1. Acceptance of terms" },
      body: {
        vi: "Việc bạn đánh dấu đồng ý khi đăng ký, hoặc tiếp tục sử dụng Dịch vụ, đồng nghĩa với việc bạn chấp nhận các Điều khoản này. Nếu bạn sử dụng Dịch vụ thay mặt một tổ chức, bạn cam kết có thẩm quyền ràng buộc tổ chức đó với các Điều khoản.",
        en: "Checking the consent box at registration, or continuing to use the Service, means you accept these Terms. If you use the Service on behalf of an organization, you represent that you are authorized to bind that organization to these Terms.",
      },
    },
    {
      heading: { vi: "2. Định nghĩa", en: "2. Definitions" },
      list: {
        vi: [
          "“Agromind AI”, “chúng tôi”: đơn vị vận hành Dịch vụ.",
          "“Người dùng”, “bạn”: cá nhân hoặc tổ chức sử dụng Dịch vụ.",
          "“Nội dung người dùng”: ảnh lá cây, mô tả triệu chứng, ghi chú, vị trí vườn và dữ liệu khác bạn cung cấp.",
          "“Kết quả AI”: gợi ý bệnh, độ tin cậy, khuyến nghị và nội dung do hệ thống AI tạo ra.",
          "“Gói dịch vụ”: các mức sử dụng có tính phí hoặc miễn phí (Seed, Grow, Bloom, Elite).",
        ],
        en: [
          "“Agromind AI”, “we”, “us”: the operator of the Service.",
          "“User”, “you”: the individual or organization using the Service.",
          "“User Content”: leaf images, symptom descriptions, notes, garden locations and other data you provide.",
          "“AI Results”: disease suggestions, confidence scores, recommendations and content generated by the AI system.",
          "“Plans”: the free or paid usage tiers (Seed, Grow, Bloom, Elite).",
        ],
      },
    },
    {
      heading: { vi: "3. Điều kiện sử dụng và tài khoản", en: "3. Eligibility and account" },
      list: {
        vi: [
          "Bạn phải đủ 15 tuổi trở lên, hoặc có sự đồng ý của người giám hộ hợp pháp, để tạo tài khoản.",
          "Bạn phải cung cấp thông tin chính xác và giữ cho thông tin luôn cập nhật.",
          "Bạn chịu trách nhiệm bảo mật mật khẩu và mọi hoạt động diễn ra dưới tài khoản của mình.",
          "Vui lòng thông báo cho chúng tôi ngay khi phát hiện truy cập trái phép vào tài khoản.",
        ],
        en: [
          "You must be at least 15 years old, or have the consent of a legal guardian, to create an account.",
          "You must provide accurate information and keep it up to date.",
          "You are responsible for keeping your password secure and for all activity under your account.",
          "Please notify us promptly if you detect unauthorized access to your account.",
        ],
      },
    },
    {
      heading: { vi: "4. Mô tả dịch vụ", en: "4. Service description" },
      body: {
        vi: "Agromind AI giúp người trồng cây quan sát sức khỏe cây từ ảnh lá: xác thực ảnh, gợi ý khả năng bệnh kèm độ tin cậy, đối chiếu triệu chứng với nguồn tham khảo, lưu lịch sử, theo dõi thời tiết và lập kế hoạch chăm sóc. Dịch vụ có thể được cập nhật, thay đổi hoặc ngừng một phần theo thời gian.",
        en: "Agromind AI helps growers observe plant health from leaf photos: validating images, suggesting likely diseases with confidence scores, cross-checking symptoms against references, saving history, tracking weather and planning care. The Service may be updated, changed or partially discontinued over time.",
      },
    },
    {
      heading: { vi: "5. Bản chất tham khảo của kết quả AI (quan trọng)", en: "5. AI Results are advisory only (important)" },
      body: {
        vi: "Kết quả AI chỉ mang tính hỗ trợ và tham khảo, KHÔNG phải chẩn đoán chính thức và KHÔNG thay thế ý kiến của chuyên gia nông nghiệp, bảo vệ thực vật hoặc thú y. Chúng tôi không bảo đảm độ chính xác tuyệt đối. Bạn tự chịu trách nhiệm với mọi quyết định canh tác, bao gồm việc dùng thuốc bảo vệ thực vật, phân bón hay xử lý cây trồng. Khi bệnh lây lan nhanh, thiệt hại lớn hoặc cần dùng thuốc, hãy hỏi ý kiến chuyên gia địa phương và tuân thủ quy định pháp luật về vật tư nông nghiệp.",
        en: "AI Results are supportive and for reference only. They are NOT an official diagnosis and do NOT replace the advice of an agronomist, plant-protection or veterinary professional. We do not guarantee absolute accuracy. You are solely responsible for all farming decisions, including the use of pesticides, fertilizers or plant treatments. When a disease spreads quickly, causes major damage, or pesticides are involved, consult a local expert and comply with laws on agricultural inputs.",
      },
    },
    {
      heading: { vi: "6. Trách nhiệm của người dùng", en: "6. User responsibilities" },
      list: {
        vi: [
          "Chỉ sử dụng Dịch vụ cho mục đích hợp pháp và đúng với Điều khoản.",
          "Không tải lên nội dung vi phạm pháp luật, xâm phạm quyền của người khác hoặc chứa mã độc.",
          "Không cố gắng dò quét, can thiệp, làm quá tải hệ thống hoặc truy cập trái phép.",
          "Không dùng công cụ tự động để lạm dụng các tính năng AI nhằm gây tốn kém tài nguyên.",
          "Không sao chép, bán lại hoặc khai thác thương mại Dịch vụ khi chưa được phép.",
        ],
        en: [
          "Use the Service only for lawful purposes and in accordance with these Terms.",
          "Do not upload content that is illegal, infringes others' rights or contains malware.",
          "Do not attempt to scan, interfere with, overload the system or gain unauthorized access.",
          "Do not use automated tools to abuse the AI features and drive up resource costs.",
          "Do not copy, resell or commercially exploit the Service without permission.",
        ],
      },
    },
    {
      heading: { vi: "7. Nội dung do người dùng cung cấp", en: "7. User Content" },
      body: {
        vi: "Bạn giữ quyền sở hữu đối với Nội dung người dùng của mình. Khi tải lên, bạn cấp cho Agromind AI quyền được lưu trữ, xử lý và phân tích nội dung đó nhằm cung cấp và cải thiện Dịch vụ (ví dụ: gửi ảnh đến hệ thống nhận diện, đối chiếu triệu chứng). Bạn cam kết có quyền hợp pháp đối với nội dung mình tải lên. Chúng tôi không chủ động chia sẻ Nội dung người dùng ra công khai.",
        en: "You retain ownership of your User Content. By uploading it, you grant Agromind AI the right to store, process and analyze that content to provide and improve the Service (for example, sending images to the recognition system, cross-checking symptoms). You represent that you have the legal right to the content you upload. We do not proactively make User Content public.",
      },
    },
    {
      heading: { vi: "8. Gói dịch vụ, thanh toán và hoàn tiền", en: "8. Plans, payment and refunds" },
      list: {
        vi: [
          "Gói Seed miễn phí; các gói Grow, Bloom, Elite tính phí theo chu kỳ trả trước. Thời hạn của mỗi lần thanh toán được ghi rõ trên trang Bảng giá và trên màn hình thanh toán trước khi bạn chuyển tiền.",
          "Thanh toán được xử lý qua chuyển khoản ngân hàng thông qua đối tác SePay. Gói chỉ được kích hoạt sau khi hệ thống xác nhận nhận đủ tiền với đúng nội dung chuyển khoản.",
          "Gói KHÔNG tự động gia hạn; khi hết thời hạn bạn cần chủ động thanh toán lại nếu muốn tiếp tục.",
          "Chuyển khoản thiếu, thừa, sai nội dung hoặc quá hạn có thể cần đối soát thủ công và làm chậm kích hoạt.",
          "Do đặc thù dịch vụ số kích hoạt ngay, các khoản đã thanh toán thường không được hoàn lại, trừ trường hợp lỗi kỹ thuật từ phía chúng tôi khiến bạn không sử dụng được gói. Yêu cầu hỗ trợ vui lòng gửi trong 7 ngày.",
          "Giá và quyền lợi từng gói có thể thay đổi; thay đổi không áp dụng hồi tố cho chu kỳ đã thanh toán.",
        ],
        en: [
          "The Seed plan is free; Grow, Bloom and Elite are prepaid. The term each payment buys is stated on the Pricing page and on the checkout screen before you transfer any money.",
          "Payments are processed by bank transfer through our partner SePay. A plan is activated only after the system confirms the correct amount has been received with the correct transfer content.",
          "Plans do NOT auto-renew; when the term ends you must actively pay again to continue.",
          "Underpaid, overpaid, mislabeled or late transfers may require manual reconciliation and delay activation.",
          "Because this is a digital service activated immediately, paid amounts are generally non-refundable, except where a technical fault on our side prevents you from using the plan. Support requests should be sent within 7 days.",
          "Prices and plan benefits may change; changes do not apply retroactively to an already-paid cycle.",
        ],
      },
    },
    {
      heading: { vi: "9. Sở hữu trí tuệ", en: "9. Intellectual property" },
      body: {
        vi: "Dịch vụ, bao gồm giao diện, mã nguồn, thương hiệu, logo và mô hình AI, thuộc quyền sở hữu của Agromind AI hoặc các bên cấp phép. Bạn không được sử dụng các tài sản này ngoài phạm vi mà Điều khoản cho phép. Một số hình ảnh minh họa cây trồng thuộc về các nguồn bên thứ ba và được ghi nguồn tương ứng.",
        en: "The Service, including its interface, source code, branding, logos and AI models, is owned by Agromind AI or its licensors. You may not use these assets beyond what these Terms permit. Some illustrative crop images belong to third-party sources and are credited accordingly.",
      },
    },
    {
      heading: { vi: "10. Dịch vụ bên thứ ba", en: "10. Third-party services" },
      body: {
        vi: "Dịch vụ tích hợp một số nền tảng bên thứ ba, ví dụ: DeepSeek và Tavily (xử lý và tìm nguồn cho phần đối chiếu triệu chứng), Hugging Face (chạy mô hình nhận diện ảnh), Google (đăng nhập), Microsoft Clarity (phân tích trải nghiệm), SePay (thanh toán), Supabase, Vercel và Render (hạ tầng). Việc sử dụng các dịch vụ này có thể chịu điều khoản riêng của bên thứ ba. Chúng tôi không chịu trách nhiệm cho hoạt động của các bên thứ ba nằm ngoài kiểm soát của mình.",
        en: "The Service integrates several third-party platforms, e.g. DeepSeek and Tavily (processing and sourcing for symptom cross-checking), Hugging Face (running the image recognition model), Google (sign-in), Microsoft Clarity (experience analytics), SePay (payments), Supabase, Vercel and Render (infrastructure). Use of these may be subject to the third parties' own terms. We are not responsible for the actions of third parties beyond our control.",
      },
    },
    {
      heading: { vi: "11. Quyền riêng tư", en: "11. Privacy" },
      body: {
        vi: "Việc thu thập và xử lý dữ liệu cá nhân được mô tả trong Chính sách quyền riêng tư của chúng tôi. Bằng việc sử dụng Dịch vụ, bạn đồng ý với các thực hành nêu trong chính sách đó.",
        en: "Our collection and processing of personal data is described in our Privacy Policy. By using the Service, you consent to the practices described there.",
      },
    },
    {
      heading: { vi: "12. Tuyên bố miễn trừ bảo đảm", en: "12. Disclaimer of warranties" },
      body: {
        vi: "Dịch vụ được cung cấp “như hiện có” và “theo khả năng sẵn có”. Trong phạm vi pháp luật cho phép, chúng tôi không đưa ra bảo đảm nào về tính chính xác, không gián đoạn, không lỗi hoặc phù hợp cho một mục đích cụ thể. Dịch vụ có thể tạm ngưng để bảo trì hoặc do giới hạn hạ tầng.",
        en: "The Service is provided “as is” and “as available”. To the extent permitted by law, we make no warranty of accuracy, uninterrupted or error-free operation, or fitness for a particular purpose. The Service may be suspended for maintenance or due to infrastructure limits.",
      },
    },
    {
      heading: { vi: "13. Giới hạn trách nhiệm", en: "13. Limitation of liability" },
      body: {
        vi: "Trong phạm vi pháp luật cho phép, Agromind AI không chịu trách nhiệm cho các thiệt hại gián tiếp, ngẫu nhiên hoặc hậu quả, bao gồm thiệt hại mùa màng, mất lợi nhuận hay mất dữ liệu, phát sinh từ việc sử dụng hoặc không thể sử dụng Dịch vụ hay từ việc dựa vào Kết quả AI. Tổng trách nhiệm của chúng tôi, nếu có, không vượt quá số tiền bạn đã thanh toán cho Dịch vụ trong 3 tháng gần nhất.",
        en: "To the extent permitted by law, Agromind AI is not liable for indirect, incidental or consequential damages, including crop loss, lost profits or lost data, arising from your use of or inability to use the Service, or from reliance on AI Results. Our total liability, if any, will not exceed the amount you paid for the Service in the preceding 3 months.",
      },
    },
    {
      heading: { vi: "14. Bồi thường", en: "14. Indemnification" },
      body: {
        vi: "Bạn đồng ý bồi thường và giữ cho Agromind AI không bị thiệt hại trước các khiếu nại phát sinh từ việc bạn vi phạm Điều khoản, vi phạm pháp luật hoặc xâm phạm quyền của bên thứ ba.",
        en: "You agree to indemnify and hold Agromind AI harmless from claims arising out of your breach of these Terms, violation of law, or infringement of third-party rights.",
      },
    },
    {
      heading: { vi: "15. Tạm ngưng và chấm dứt", en: "15. Suspension and termination" },
      body: {
        vi: "Chúng tôi có thể tạm ngưng hoặc chấm dứt quyền truy cập của bạn nếu bạn vi phạm Điều khoản hoặc gây rủi ro cho hệ thống và người dùng khác. Bạn có thể ngừng sử dụng và yêu cầu xóa tài khoản bất cứ lúc nào. Một số điều khoản (sở hữu trí tuệ, giới hạn trách nhiệm, bồi thường) vẫn có hiệu lực sau khi chấm dứt.",
        en: "We may suspend or terminate your access if you breach these Terms or pose a risk to the system and other users. You may stop using the Service and request account deletion at any time. Certain sections (intellectual property, limitation of liability, indemnification) survive termination.",
      },
    },
    {
      heading: { vi: "16. Thay đổi dịch vụ và điều khoản", en: "16. Changes to the Service and Terms" },
      body: {
        vi: "Chúng tôi có thể cập nhật Điều khoản theo thời gian. Khi có thay đổi quan trọng, chúng tôi sẽ thông báo hợp lý (ví dụ qua ứng dụng hoặc email). Việc bạn tiếp tục sử dụng Dịch vụ sau khi thay đổi có hiệu lực đồng nghĩa với việc chấp nhận Điều khoản mới.",
        en: "We may update these Terms from time to time. For material changes we will give reasonable notice (for example in-app or by email). Your continued use of the Service after changes take effect means you accept the updated Terms.",
      },
    },
    {
      heading: { vi: "17. Luật áp dụng và giải quyết tranh chấp", en: "17. Governing law and disputes" },
      body: {
        vi: "Điều khoản được điều chỉnh bởi pháp luật Việt Nam. Các tranh chấp sẽ được ưu tiên giải quyết bằng thương lượng; nếu không đạt được, sẽ được giải quyết tại tòa án có thẩm quyền tại Việt Nam.",
        en: "These Terms are governed by the laws of Vietnam. Disputes will first be resolved through negotiation; failing that, they will be resolved by a competent court in Vietnam.",
      },
    },
    {
      heading: { vi: "18. Liên hệ", en: "18. Contact" },
      body: {
        vi: `Mọi câu hỏi về Điều khoản, vui lòng liên hệ: ${CONTACT_EMAIL}.`,
        en: `For questions about these Terms, please contact: ${CONTACT_EMAIL}.`,
      },
    },
  ],
};

export const privacyDoc: LegalDoc = {
  title: { vi: "Chính sách quyền riêng tư", en: "Privacy Policy" },
  intro: {
    vi: "Chính sách này giải thích Agromind AI thu thập, sử dụng, chia sẻ và bảo vệ dữ liệu cá nhân của bạn như thế nào khi bạn dùng Dịch vụ. Chúng tôi tôn trọng quyền riêng tư của bạn và chỉ thu thập dữ liệu cần thiết để vận hành và cải thiện Dịch vụ.",
    en: "This policy explains how Agromind AI collects, uses, shares and protects your personal data when you use the Service. We respect your privacy and collect only the data needed to operate and improve the Service.",
  },
  sections: [
    {
      heading: { vi: "1. Phạm vi áp dụng", en: "1. Scope" },
      body: {
        vi: "Chính sách áp dụng cho website, ứng dụng và các dịch vụ liên quan của Agromind AI. Bằng việc tạo tài khoản và đánh dấu đồng ý, bạn xác nhận đã đọc và đồng ý với chính sách này.",
        en: "This policy applies to the Agromind AI website, application and related services. By creating an account and checking the consent box, you confirm you have read and agree to this policy.",
      },
    },
    {
      heading: { vi: "2. Dữ liệu chúng tôi thu thập", en: "2. Data we collect" },
      list: {
        vi: [
          "Thông tin tài khoản: email, mật khẩu (được băm), tên hiển thị, ảnh đại diện (nếu có).",
          "Nội dung chẩn đoán: ảnh lá bạn tải lên, mô tả triệu chứng, kết quả, ghi chú và lịch sử kiểm tra.",
          "Vị trí vườn: tọa độ hoặc địa chỉ bạn nhập để xem thời tiết và lập kế hoạch (chỉ khi bạn cung cấp).",
          "Thông tin thanh toán: mã đơn, nội dung và trạng thái chuyển khoản xử lý qua SePay. Chúng tôi KHÔNG lưu số thẻ hay thông tin ngân hàng đầy đủ của bạn.",
          "Dữ liệu phân tích trải nghiệm: qua Microsoft Clarity, gồm thao tác, heatmap và có thể có ghi lại phiên (session recording) để cải thiện giao diện.",
          "Dữ liệu đăng nhập Google (nếu bạn dùng): địa chỉ email và thông tin hồ sơ cơ bản do Google cung cấp.",
          "Dữ liệu kỹ thuật: loại thiết bị, trình duyệt, địa chỉ IP và nhật ký truy cập cơ bản.",
        ],
        en: [
          "Account information: email, password (hashed), display name, avatar (if any).",
          "Diagnosis content: leaf images you upload, symptom descriptions, results, notes and check history.",
          "Garden location: coordinates or an address you enter for weather and planning (only when you provide it).",
          "Payment information: order code, transfer content and status processed through SePay. We do NOT store your card number or full bank details.",
          "Experience analytics: via Microsoft Clarity, including interactions, heatmaps and possibly session recordings to improve the interface.",
          "Google sign-in data (if used): the email address and basic profile information provided by Google.",
          "Technical data: device type, browser, IP address and basic access logs.",
        ],
      },
    },
    {
      heading: { vi: "3. Cách chúng tôi sử dụng dữ liệu", en: "3. How we use data" },
      list: {
        vi: [
          "Cung cấp và vận hành Dịch vụ: xác thực ảnh, tạo kết quả, lưu lịch sử, thời tiết, kế hoạch.",
          "Xác thực tài khoản và bảo mật, phòng chống lạm dụng.",
          "Xử lý thanh toán và kích hoạt gói dịch vụ.",
          "Cải thiện chất lượng, giao diện và độ tin cậy của Dịch vụ.",
          "Liên hệ với bạn về tài khoản, thay đổi quan trọng hoặc hỗ trợ khi cần.",
        ],
        en: [
          "Provide and operate the Service: validate images, generate results, save history, weather, plans.",
          "Authenticate accounts and provide security, preventing abuse.",
          "Process payments and activate plans.",
          "Improve the quality, interface and reliability of the Service.",
          "Contact you about your account, material changes or support when needed.",
        ],
      },
    },
    {
      heading: { vi: "4. Cơ sở xử lý", en: "4. Basis for processing" },
      body: {
        vi: "Chúng tôi xử lý dữ liệu dựa trên sự đồng ý của bạn khi đăng ký, để thực hiện hợp đồng cung cấp Dịch vụ, và cho các lợi ích hợp pháp như bảo mật và cải thiện sản phẩm. Bạn có thể rút lại sự đồng ý bằng cách ngừng sử dụng và yêu cầu xóa dữ liệu.",
        en: "We process data based on your consent at registration, to perform the contract of providing the Service, and for legitimate interests such as security and product improvement. You may withdraw consent by stopping use and requesting deletion.",
      },
    },
    {
      heading: { vi: "5. Chia sẻ với bên thứ ba", en: "5. Sharing with third parties" },
      body: {
        vi: "Chúng tôi không bán dữ liệu cá nhân của bạn. Chúng tôi chỉ chia sẻ dữ liệu cần thiết với các nhà cung cấp giúp vận hành Dịch vụ: Hugging Face (chạy mô hình nhận diện ảnh), DeepSeek và Tavily (xử lý và tìm nguồn cho phần đối chiếu triệu chứng), Google (đăng nhập), SePay (thanh toán), Microsoft Clarity (phân tích trải nghiệm), Supabase (cơ sở dữ liệu), Vercel và Render (hạ tầng máy chủ). Một số nhà cung cấp có thể đặt máy chủ ngoài Việt Nam.",
        en: "We do not sell your personal data. We share only the data necessary with providers that help operate the Service: Hugging Face (running the image recognition model), DeepSeek and Tavily (processing and sourcing for symptom cross-checking), Google (sign-in), SePay (payments), Microsoft Clarity (experience analytics), Supabase (database), Vercel and Render (server infrastructure). Some providers may host servers outside Vietnam.",
      },
    },
    {
      heading: { vi: "6. Cookie và công nghệ theo dõi", en: "6. Cookies and tracking" },
      body: {
        vi: "Chúng tôi dùng bộ nhớ trình duyệt để ghi nhớ phiên đăng nhập, ngôn ngữ và giao diện. Microsoft Clarity dùng cookie và mã theo dõi để tạo heatmap và có thể ghi lại phiên tương tác (ẩn phần lớn nội dung nhạy cảm) nhằm cải thiện trải nghiệm. Bạn có thể chặn cookie qua trình duyệt, tuy nhiên một số tính năng có thể không hoạt động đầy đủ.",
        en: "We use browser storage to remember your login session, language and theme. Microsoft Clarity uses cookies and tracking code to build heatmaps and may record interaction sessions (masking most sensitive content) to improve the experience. You can block cookies in your browser, though some features may not work fully.",
      },
    },
    {
      heading: { vi: "7. Lưu trữ và thời gian lưu", en: "7. Storage and retention" },
      body: {
        vi: "Dữ liệu tài khoản và chẩn đoán được lưu trong cơ sở dữ liệu (Supabase) chừng nào tài khoản còn hoạt động. Khi bạn yêu cầu xóa tài khoản, chúng tôi sẽ xóa hoặc ẩn danh dữ liệu cá nhân trong thời gian hợp lý, trừ phần cần giữ lại theo yêu cầu pháp luật (ví dụ hồ sơ thanh toán).",
        en: "Account and diagnosis data is stored in our database (Supabase) for as long as the account is active. When you request account deletion, we will delete or anonymize personal data within a reasonable time, except data we must retain by law (e.g. payment records).",
      },
    },
    {
      heading: { vi: "8. Bảo mật", en: "8. Security" },
      body: {
        vi: "Chúng tôi áp dụng các biện pháp bảo mật hợp lý: mã hóa truyền tải HTTPS, băm mật khẩu, xác thực chữ ký cho webhook thanh toán, giới hạn tần suất và các tiêu đề bảo mật. Tuy nhiên, không hệ thống nào an toàn tuyệt đối; bạn cũng nên bảo vệ mật khẩu của mình.",
        en: "We apply reasonable security measures: HTTPS in transit, password hashing, signature verification for payment webhooks, rate limiting and security headers. However, no system is perfectly secure; you should also protect your own password.",
      },
    },
    {
      heading: { vi: "9. Quyền của bạn", en: "9. Your rights" },
      list: {
        vi: [
          "Truy cập và xem dữ liệu cá nhân của bạn trong ứng dụng.",
          "Chỉnh sửa thông tin hồ sơ.",
          "Yêu cầu xóa tài khoản và dữ liệu cá nhân liên quan.",
          "Rút lại sự đồng ý cho việc xử lý dữ liệu (có thể ảnh hưởng khả năng dùng Dịch vụ).",
        ],
        en: [
          "Access and view your personal data in the app.",
          "Edit your profile information.",
          "Request deletion of your account and related personal data.",
          "Withdraw consent for data processing (this may affect your ability to use the Service).",
        ],
      },
    },
    {
      heading: { vi: "10. Trẻ em", en: "10. Children" },
      body: {
        vi: "Dịch vụ không hướng đến trẻ em dưới 15 tuổi. Nếu bạn cho rằng một trẻ vị thành niên đã cung cấp dữ liệu mà không có sự đồng ý của người giám hộ, vui lòng liên hệ để chúng tôi xử lý.",
        en: "The Service is not directed at children under 15. If you believe a minor has provided data without a guardian's consent, please contact us so we can address it.",
      },
    },
    {
      heading: { vi: "11. Thay đổi chính sách", en: "11. Changes to this policy" },
      body: {
        vi: "Chúng tôi có thể cập nhật chính sách này theo thời gian. Khi có thay đổi quan trọng, chúng tôi sẽ thông báo hợp lý và cập nhật ngày ở đầu trang.",
        en: "We may update this policy from time to time. For material changes we will give reasonable notice and update the date at the top of the page.",
      },
    },
    {
      heading: { vi: "12. Liên hệ", en: "12. Contact" },
      body: {
        vi: `Về quyền riêng tư và dữ liệu, vui lòng liên hệ: ${CONTACT_EMAIL}.`,
        en: `For privacy and data matters, please contact: ${CONTACT_EMAIL}.`,
      },
    },
  ],
};
